name: CI Development

on:
  push:
    branches:
      - '!master'

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - uses: einaregilsson/build-number@v2
        with:
          token: ${{secrets.github_token}}
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.4'
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: |
          npm ci
          npm uninstall -g @angular/cli
          npm install -g @angular/cli
      - name: Set Version
        run: sed -i "s/\[ci-version\]/${GITHUB_REF##*/}-$BUILD_NUMBER/g" ./version.ts
      - name: Build Library
        run: ng build --project sc-clr-autocomplete --prod
