name: CI

on:
  push:
    branches: 
      - master

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.4'
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: |
          npm ci
          npm uninstall -g @angular/cli
          npm install -g @angular/cli
      - name: Build Library
        run: ng build --project sc-clr-autocomplete
# - name: Publish Library to NPM
#   run: npm publish ./dist/sc-clr-autocomplete
#   env:
#     NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Publish Github Pages
        run: ng deploy --project demo --base-href=/sc-clr-autocomplete/ --name='Scenius CI (GitHub)' --email='ci_github@scenius.nl' --message='Deploy latest master branch to GitHub Pages' --repo=https://${{secrets.GITHUB_PAGES_TOKEN}}@github.com/scenius-software/sc-clr-autocomplete.git
