name: CI

on:
  push:
    branches: 
      - master

jobs:
  build-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.4'
          registry-url: https://registry.npmjs.org
      - name: Build library
        run: |
          npm ci
          npm uninstall -g @angular/cli
          npm install -g @angular/cli
          npm install -g ngh
          ng build --project sc-clr-autocomplete        
          npm publish ./dist/sc-clr-autocomplete
          npm build --prod --project demo --base-href https://scenius-software.github.io/sc-clr-autocomplete/
          ngh --dir=dist/demo --repo=https://${{secrets.GITHUB_PAGES_TOKEN}}@githubcom/scenius-software/sc-clr-autocomplete.git
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
